[project]
name = "microtonal-init-presets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Xerydian", email = "xerydian@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jinja2>=3.1.6",
]

[project.scripts]
generate-presets = "microtonal_init_presets:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
